name: CI/CD - Build & Deploy to Cloud Run (Artifact Registry + Terraform)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCP credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > infra/key.json
          gcloud auth activate-service-account RunSAPawait@pawait-470513.iam.gserviceaccount.com --key-file=infra/key.json
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set image tag
        run: |
          echo "IMAGE_URI=us-central1-docker.pkg.dev/pawait-470513/insight-agent-repo/insight-agent:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_URI .

      - name: Push Docker image
        run: docker push $IMAGE_URI

      - name: Terraform init
        working-directory: ./infra
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: ./infra
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
        run: |
          terraform apply -auto-approve \
            -var="project_id=pawait-470513" \
            -var="region=us-central1" \
            -var="image=${IMAGE_URI}"
